### ISSUE TITLE
How did you do that 'poll(String url, FeedProvider feedProvider)' invokation worked properly?

### ISSUE THREAD

**Issue by coloal** [kaliy/kafka-connect-rss#5]
So I am developing a connector and I was looking at your code and I saw that you overwrote the poll() method with two parameters. And I wanted to do this too in order to do a dependency injection via these parameters but I do not understand how your code works. I mean how does the code invoking poll(String, FeedProvider) do it properly? As far as I know I can't touch the code in charge of invoking 'start' and 'poll' so: How did you do it to initialize both objects, String and FeedProvider, and pass them as parameters when invoking 'poll'?

**Comment by kaliy** [comment]
Hi, not sure if I got the question correctly.

The connector framework does not call the `poll(String, FeedProvider)` method, it is a private method that is being called by the `poll()` from the `SourceTask` interface. The FeedProvider instances are initialized in the start(...) method.

**Comment by coloal** [comment]
Ok, so for unit testing I guess you had to use something like PowerMockito in order to mock the objects that were initialized inside the class and represented a dependency, right? I was just trying to add a parameter to poll() in order to do a dependency injection and avoid to mock an object inside the class but I suppose there is no other possibility than this.

**Comment by kaliy** [comment]
ok, now I got the question :)

As feed providers are created using factory, you can substitute it. I mocked them using mockito and you can find some examples in the RssSourceTaskTest: https://github.com/kaliy/kafka-connect-rss/blob/master/src/test/java/org/kaliy/kafka/connect/rss/RssSourceTaskTest.java

**Comment by kaliy** [comment]
Overall, regarding testing I suggest to check the test classes as every class is covered by unit tests and also there is an example of the integration test for the connector (RssSourceConnectorIntegrationTest)

**Comment by coloal** [comment]
Yes I am founding your testing pretty helpful, but does not adding a 'public void setFeedProvider(Feed)' in RssSourceTask just in order to be able to mock the FeedProvider is a bad design? I mean is the easiest way to solve the problem but you are changing your API just for testing.

**Comment by kaliy** [comment]
From the standpoing of the RssSourceTask the `Function<Map<String, String>, RssSourceConnectorConfig>` and  `Function<String, FeedProvider>` instances is something external - they are factories that creates objects. You can name them RssSourceConnectorConfigFactory and FeedProviderFactory but it's easier to just use new java8 interfaces.

Usually you inject such dependencies using constructor but it's not possible because the SourceTask implementation is created by framework using default constructor.

As for the providing additional method for setting the dependency - it's done for the sake of testability. Mockito documentation has two options for mocking new object creations and I used the second one - factory: https://github.com/mockito/mockito/wiki/Mocking-Object-Creation

**Comment by coloal** [comment]
Ok, thanks man. Did it the way you mention with mockito.
